/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useEffect, useRef, useState } from 'react'
import { useCursor, useGLTF } from '@react-three/drei'
import gsap from 'gsap'
import { useFrame } from '@react-three/fiber'

export function Post(props) {
  const { nodes, materials } = useGLTF('/models/post.glb')
  const snowDepth = props.snowDepth
  const doorFront = useRef()
  const doorBack = useRef()
  const snowRoof = useRef()
  const [hovered, setHovered] = useState(false)

  useEffect(() => {
    if (!doorFront.current || !doorBack.current) return

    gsap.to(doorFront.current.rotation, {
      x: hovered ? Math.PI / 2 : 0,
      duration: 0.5,
      ease: 'power2.out'
    })

    gsap.to(doorBack.current.rotation, {
      x: hovered ? Math.PI / 2 : Math.PI,
      duration: 0.5,
      ease: 'power2.out'
    })

  }, [hovered])

  useCursor(hovered)

  useFrame(() => {
    if (!snowRoof.current) return

    const targetPos = THREE.MathUtils.clamp(
      THREE.MathUtils.mapLinear(snowDepth, 0, 0.5, 3.646, 3.716), 3.646, 3.716
    )

    snowRoof.current.position.y = THREE.MathUtils.lerp(
      snowRoof.current.position.y,
      targetPos,
      0.05
    )
  })

  return (
    <group {...props} dispose={null} scale={0.1} position={[0.1, 0.02, -0.6]}
      onPointerOver={() => setHovered(true)}
      onPointerOut={() => setHovered(false)}
      onClick={() => {
        window.open('mailto:soon.syp@gmail.com')
      }}
    >
      <mesh
        ref={snowRoof}
        castShadow
        receiveShadow
        geometry={nodes.snowRoof.geometry}
        material={materials.snow}
        position={[0, 3.646, 0]}
        scale={[0.518, 0.518, 0.784]}
        visible={snowDepth >= 0.1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pillar002.geometry}
        material={materials.red}
        position={[0, 1.611, 0]}
        scale={[0.11, 1.8, 0.11]}
      />
      <group position={[0, 3.842, 0]} scale={[0.455, 0.455, 0.645]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube422.geometry} material={materials.red} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube422_1.geometry}
          material={materials.darkRed}
        />
      </group>
      <group position={[0, 3.722, 0]} scale={[0.518, 0.518, 0.794]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube423.geometry} material={materials.red} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube423_1.geometry}
          material={materials.darkRed}
        />
      </group>
      <group ref={doorFront} position={[0, 3.386, 0.649]} scale={[0.455, 0.455, 0.645]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube427.geometry} material={materials.red} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube427_1.geometry}
          material={materials.snow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube427_2.geometry}
          material={materials.darkRed}
        />
      </group>
      <group ref={doorBack}
        position={[0, 3.386, -0.64]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.455, 0.455, 0.645]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube500.geometry} material={materials.red} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube500_1.geometry}
          material={materials.snow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube500_2.geometry}
          material={materials.darkRed}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/post.glb')