/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { param, useIsDebug } from '@/lib/param'
import { useHelper } from "@react-three/drei"
import * as THREE from 'three'

export function Streetlight({ progress }) {
  const { nodes, materials } = useGLTF('models/streetlight.glb')
  const spotLightRef = useRef()
  const target = useRef()
  const isDebug = useIsDebug()
  const isDay = progress >= 0.25 && progress <= 0.75

    useHelper(isDebug ? spotLightRef : null, THREE.SpotLightHelper, '#fff')

  useEffect(() => {
    spotLightRef.current.target = target.current
  }, [])

  return (
    <group scale={param.groundRadius * 2} position={param.groundPos}>
      <group dispose={null} scale={1} position={[0.5, 0.01, -0.3]} rotation-y={-Math.PI * 0.2}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pillar001.geometry}
          material={materials.streetlight}
          position={[0, 0.063, 0]}
          scale={[0.068, 0.022, 0.068]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.hex.geometry}
          material={materials.streetlight}
          position={[0, 0.027, 0]}
          scale={[0.101, 0.035, 0.101]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lightHead.geometry}
          material={materials.streetlight}
          position={[0, 0.791, 0.188]}
          scale={[-0.05, -0.039, -0.05]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.light.geometry}
          material={materials.light}
          position={[0, 0.791, 0.188]}
          scale={[-0.047, -0.038, -0.047]}
        >
          {isDay ?
            <meshStandardMaterial color="#c0c0c0" /> :
            <meshBasicMaterial color="#ffea09" />
          }
        </mesh>
      </group>

      <spotLight castShadow
        ref={spotLightRef}
        position={param.streetlightPos}
        angle={0.9}
        penumbra={0.5}
        intensity={isDay ? 0 : 200}
        distance={100}
        shadow-mapSize={[2048, 2048]}
        shadow-camera-near={0.1}
        shadow-camera-far={1}
        shadow-bias={-0.0001}
        shadow-normalBias={0.02}
      />

      <object3D ref={target} position={param.streetlightTargetPos} />

    </group>
  )
}

useGLTF.preload('models/streetlight.glb')