/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { useFrame, useLoader } from '@react-three/fiber'
import { tempColorIndex, tempColorList } from '@/lib/param'

export default function Thermometer({ temp, snowDepth, weather }) {
  const { nodes, materials } = useGLTF('/models/thermometer.glb')
  const tempValue = temp ?? weather.current.temperature
  const liquidRef = useRef()
  const liquidMaterialRef = useRef()
  const screenRef = useRef([])
  const snowRef = useRef([])
  const snowScreenRef = useRef()

  const normalFace = useLoader(THREE.TextureLoader, '/textures/face/normal.png')
  const blazingFace = useLoader(THREE.TextureLoader, '/textures/face/blazing.png')
  const hotFace = useLoader(THREE.TextureLoader, '/textures/face/hot.png')
  const warmFace = useLoader(THREE.TextureLoader, '/textures/face/warm.png')
  const coldFace = useLoader(THREE.TextureLoader, '/textures/face/cold.png')
  const freezeFace = useLoader(THREE.TextureLoader, '/textures/face/freeze.png')

  useEffect(() => {
    if (!liquidMaterialRef.current) return
  
    let face
    const visible = tempValue != null

    screenRef.current.forEach(material => {
      if (!material) return

      material.transparent = true
      material.opacity = visible ? 1 : 0
    })

    if (tempValue < 0) {
      face = freezeFace
    } else if (tempValue <= 10) {
      face = coldFace
    } else if (tempValue <= 25) {
      face = normalFace
    } else if (tempValue <= 30) {
      face = warmFace
    } else if (tempValue <= 35) {
      face = hotFace
    } else {
      face = blazingFace
    }

    const color = tempColorList[tempColorIndex(tempValue)]

    screenRef.current.forEach(material => {
      if (!material) return

      material.map = face
      material.color.set(color)
      material.needsUpdate = true
    })

    liquidMaterialRef.current.color.set(color)
  }, [tempValue])

  useFrame((_, delta) => {
    delta = Math.min(delta, 0.05)
    if (!liquidRef.current || !snowRef.current || !snowScreenRef.current) return

    const targetBtomScaleY = THREE.MathUtils.clamp(
      THREE.MathUtils.mapLinear(snowDepth, 0, 0.5, 0.001, 0.007), 0.001, 0.007
    )

    snowRef.current.forEach(el => {
      if (!el) return

      el.scale.y = THREE.MathUtils.lerp(
        el.scale.y,
        targetBtomScaleY,
        0.05
      )
    })

    const targetPos = THREE.MathUtils.clamp(
      THREE.MathUtils.mapLinear(snowDepth, 0, 0.5, 0.792, 0.7955), 0.792, 0.7955
    )

    snowScreenRef.current.position.y = THREE.MathUtils.lerp(
      snowScreenRef.current.position.y,
      targetPos,
      0.05
    )

    const targetScale = THREE.MathUtils.mapLinear(
      tempValue ?? 0, -50, 50, -0.04, 0.04
    )

    liquidRef.current.scale.y = THREE.MathUtils.lerp(
      liquidRef.current.scale.y,
      targetScale,
      delta * 5
    )
  })

  return (
    <group dispose={null} scale={17} position={[4.88, -9, -3.08]} rotation-y={-Math.PI * 0.2}>
      <mesh
        ref={el => (snowRef.current[0] = el)}
        castShadow
        receiveShadow
        geometry={nodes.snow001.geometry}
        material={materials.snow}
        position={[0.036, 0.756, -0.001]}
        scale={0.007}
        visible={snowDepth >= 0.1}
      />
      <mesh
        ref={el => (snowRef.current[1] = el)}
        castShadow
        receiveShadow
        geometry={nodes.snow002.geometry}
        material={materials.snow}
        position={[0.036, 0.581, -0.001]}
        scale={0.007}
        visible={snowDepth >= 0.1}
      />
      <mesh
        ref={snowScreenRef}
        castShadow
        receiveShadow
        geometry={nodes.screen001.geometry}
        material={materials.snow}
        position={[0.0612, 0.7955, -0.001]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.026, 0.111, 0.0256]}
        visible={snowDepth >= 0.1}
      />

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.face.geometry}
        material={materials.streetlight}
        position={[0.062, 0.791, -0.001]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.026, 0.124, 0.026]}
      >
        <meshBasicMaterial
          ref={el => (screenRef.current[0] = el)}
          map={normalFace}
          transparent
        />
      </mesh>

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.face.geometry}
        material={materials.streetlight}
        position={[0.059, 0.791, -0.001]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.026, 0.124, 0.026]}
      >
        <meshBasicMaterial
          ref={el => (screenRef.current[1] = el)}
          map={normalFace}
          transparent
        />
      </mesh>

      <mesh ref={liquidRef}
        castShadow
        receiveShadow
        geometry={nodes.liquid.geometry}
        material={nodes.liquid.material}
        position={[0.06, 0.665, -0.001]}
        scale={[0.004, 0, 0.004]}
      >
        <meshBasicMaterial
          ref={liquidMaterialRef}
          color="#fff"
        />
      </mesh>

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thermometer_.geometry}
        material={materials.streetlight}
        position={[0.019, 0.757, -0.001]}
        scale={0.007}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.glass.geometry}
        material={nodes.glass.material}
        position={[0.06, 0.665, -0.001]}
        scale={[0.005, 0.085, 0.005]}
      >
        <meshStandardMaterial
          color="#ffffff"
          metalness={0.5}
          roughness={0.1}
          side={THREE.DoubleSide}
          transparent
          opacity={0.2}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.glass002.geometry}
        material={materials.streetlight}
        position={[0.06, 0.536, -0.001]}
        scale={[0.005, 0.085, 0.005]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.glass001.geometry}
        material={materials.streetlight}
        position={[0.06, 0.676, -0.001]}
        scale={[0.005, 0.135, 0.005]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screen.geometry}
        material={materials.streetlight}
        position={[0.061, 0.791, -0.001]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.026, 0.124, 0.026]}
      />
    </group>
  )
}

useGLTF.preload('/models/thermometer.glb')