/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap'

export default function Umbrella({ precipitation, weather }) {
  const { nodes, materials } = useGLTF('/models/umbrella.glb')
  const umbrellaRef = useRef()
  const precipitationValue = precipitation ?? weather.current.precipitation

  useEffect(() => {
    if (!umbrellaRef.current) return

    const material = umbrellaRef.current.material

    material.transparent = true
    material.side = THREE.DoubleSide

    const t = THREE.MathUtils.clamp(
      precipitationValue / 5,
      0,
      1
    )

    const opacity = THREE.MathUtils.lerp(0.2, 0.9, t)

    gsap.to(material, {
      opacity,
      duration: 1,
      ease: 'power2.out'
    })

  }, [precipitationValue])

  return (
    <group dispose={null} scale={2.3} position={[0.33, -4.0, -3.05]} visible={precipitationValue > 0.3}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials.benchMetal}
        position={[1.051, 1.248, -0.015]}
        rotation={[0.062, 0.695, -0.675]}
        scale={[0.013, 0.622, 0.013]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials.yellow}
        position={[0.756, 0.735, 0.235]}
        rotation={[0.062, 0.695, -0.675]}
        scale={[0.017, 0.8, 0.017]}
      />
      <mesh ref={umbrellaRef}
        castShadow
        receiveShadow
        geometry={nodes.Sphere001.geometry}
        position={[0.952, 1.073, 0.061]}
        rotation={[0.062, 0.695, -0.675]}
        scale={0.761}
      >
        <meshStandardMaterial
          color="#ffb700"
          metalness={0.2}
          roughness={0.9}
          side={THREE.DoubleSide}
          transparent
        />
      </mesh>

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials.yellow}
        position={[1.31, 1.684, -0.203]}
        rotation={[0.062, 0.695, -0.675]}
        scale={[0.024, 1.103, 0.024]}
      />

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ribs.geometry}
        material={materials.yellow}
        position={[0.952, 1.073, 0.061]}
        rotation={[0.062, 0.695, -0.675]}
        scale={0.761}
      />
    </group>
  )
}

useGLTF.preload('/models/umbrella.glb')

