/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { param } from '@/lib/param'
import { useFrame } from '@react-three/fiber'

export default function Windvane({ windDir, windSpd }) {
  const { nodes, materials } = useGLTF('models/windvane.glb')
  const arrowRef = useRef()
  const anemometerRef = useRef()

  useFrame((_, delta) => {
    delta = Math.min(delta, 0.05)
    const arrow = arrowRef.current
    const anemometer = anemometerRef.current

    if (!arrow || !anemometer) return

    const rpm = windSpd.current * 3
    const angularSpeed = rpm * Math.PI * 2 / 60

    anemometer.rotation.y -= angularSpeed * delta
    arrow.rotation.y = windDir.current
  }, [windDir, windSpd])

  return (
    <group scale={param.groundRadius * 1.7} position={param.groundPos}>
      <group dispose={null} scale={0.3} position={[0, 0.2, 0.4]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pillar.geometry}
          material={materials.metal}
          position={[0, -0.275, 0]}
          scale={[1.785, 2.009, 1.785]}
        />
        <group ref={arrowRef}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.arrow.geometry}
            material={materials.metal}
            position={[0, 0.376, 0]}
            scale={[9.569, 0.527, 0.527]}
          >
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.arrowCenter.geometry}
            material={materials.metal}
            position={[0, 0.376, 0]}
            scale={[4.348, 0.029, 4.348]}
          >
          </mesh>
        </group>
        <group ref={anemometerRef}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere.geometry}
            material={materials.metal}
            position={[0.18, 0.716, 0.006]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={0.472}
          >
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere002.geometry}
            material={materials.metal}
            position={[-0.18, 0.716, -0.006]}
            rotation={[0, Math.PI / 2, 0]}
            scale={0.472}
          >
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere003.geometry}
            material={materials.metal}
            position={[0.006, 0.716, -0.181]}
            scale={0.472}
          >
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere004.geometry}
            material={materials.metal}
            position={[-0.005, 0.716, 0.179]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={0.472}
          >
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.center.geometry}
            material={materials.metal}
            position={[0, 0.717, 0]}
            scale={[2.91, 0.027, 2.91]}
          >
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube003.geometry}
            material={materials.metal}
            position={[0, 0.718, 0]}
            scale={[2.543, 0.298, 0.298]}
          >
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube004.geometry}
            material={materials.metal}
            position={[0, 0.718, 0]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[2.543, 0.298, 0.298]}
          >
          </mesh>
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials.metal}
          position={[0, 0.088, 0]}
          scale={[4.177, 0.449, 0.449]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials.metal}
          position={[0.001, 0.088, 0]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[3.826, 0.449, 0.449]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.west.geometry}
          material={materials.metal}
          position={[-0.488, 0, -0.001]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.318}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.east.geometry}
          material={materials.metal}
          position={[0.201, 0, -0.001]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.318}>
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.north.geometry}
          material={materials.metal}
          position={[-0.001, 0, -0.17]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.318}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.south.geometry}
          material={materials.metal}
          position={[-0.001, 0, 0.415]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.318}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005.geometry}
          material={materials.metal}
          position={[0.001, 0.004, 0]}
          scale={0.011}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006.geometry}
          material={materials.metal}
          position={[0.001, 0.004, 0]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.011}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007.geometry}
          material={materials.metal}
          position={[0.001, 0.004, 0]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={0.011}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008.geometry}
          material={materials.metal}
          position={[0.001, 0.004, 0]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.011}
        />
      </group>
    </group>
  )
}

useGLTF.preload('models/windvane.glb')